language: c
cache:
  directories:
    - $HOME/cachedir
    - $HOME/.ccache
sudo: required
dist: trusty

osx_image: xcode10.2

addons:
  homebrew:
    packages:
      - gettext
      - check
      - bullet
      - dbus
      - fontconfig
      - freetype
      - fribidi
      - gst-plugins-good
      - gstreamer
      - luajit
      - openssl
      - webp
      - libsndfile
      - glib
      - libspectre
      - libraw
      - librsvg
      - poppler
      - lz4
      - pulseaudio
      - ccache
      - ninja
      - python3
      - libffi

env:
  global:
    - EIO_MONITOR_POLL=1
    - CC="ccache gcc"
    - CXX="ccache g++"

jobs:
  include:
    - os: linux
      env: DISTRO=Fedora30 CI_BUILD_TYPE=exactness

services:
  - docker

before_install:
  - |
      if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        rm -rf $HOME/Library/Caches/Homebrew
        rm -rf $HOME/cachedir/Homebrew/Homebrew
        mv $HOME/cachedir/Homebrew $HOME/Library/Caches/Homebrew
        pip3 install meson
      fi

before_script:
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$DISTRO" != "" ]]; then
        docker pull stefanschmidt1/ci-support-files:$DISTRO
      fi
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then
        docker version
        docker run --cidfile $HOME/cid -t -d -v `pwd`:/src -v $HOME/.ccache:/root/.ccache -w /src stefanschmidt1/ci-support-files:$DISTRO bash
        cp $HOME/cachedir/config.cache . || true
      fi

  - .ci/ci-ccache-stats.sh
  - |
       if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
         cp $HOME/cachedir/config.cache . || true
       fi

script:
  - .ci/ci-configure.sh "$CI_BUILD_TYPE"
  - .ci/ci-setup-ccache.sh "$CI_BUILD_TYPE"
  - .ci/ci-make.sh "$CI_BUILD_TYPE"
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$CI_BUILD_TYPE" == "" ]]; then
          .ci/ci-make-benchmark.sh "$CI_BUILD_TYPE"
      fi
  #- .ci/ci-make-install.sh "$CI_BUILD_TYPE"
  - .ci/ci-make-check.sh "$CI_BUILD_TYPE"
  - .ci/ci-make-distcheck.sh "$CI_BUILD_TYPE"
  #- |
      #if [[ "$DISTRO" == "" ]] && [[ "$TRAVIS_OS_NAME" != "linux" ]] ; then
        #true
      #elif [[ "$CI_BUILD_TYPE" != "release-ready" ]] ; then
        #docker exec --env EIO_MONITOR_POLL=1 $(cat $HOME/cid) .ci/build-efl-app.sh
      #fi
before_cache:
  - .ci/ci-ccache-stats.sh
  - |
       mkdir -p $HOME/cachedir
       if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then
         sudo chown travis:travis $HOME/.ccache
         mkdir -p $HOME/cachedir/
         sudo cp config.cache $HOME/cachedir/
         sudo chown travis:travis $HOME/cachedir/config.cache
         sudo chown travis:travis $HOME/autom4te.cache
       else
         cp config.cache $HOME/cachedir
         mv $HOME/Library/Caches/Homebrew $HOME/cachedir/Homebrew
       fi
