language: c

sudo: required
dist: trusty

os: linux

addons:
  sonarcloud:
    organization: "stefan-schmidt-github"
script:
  - ./autogen.sh
  - build-wrapper-linux-x86-64 --out-dir bw-output make
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'
