language: c

sudo: required
dist: trusty

os: linux

addons:
  sonarcloud:
    organization: "stefan-schmidt-github"
script:
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'
