apiRules:
- exclude:
    uidRegex: ^.*NativeMethods$
- exclude:
    uidRegex: ^.*NativeStruct$
- exclude:
    uidRegex: ^.*ConstructingHandle.*$
- exclude:
    uidRegex: ^.*WrappingHandle.*$
- exclude:
    uidRegex: ^.*#ctor\(IntPtr.*$
- exclude:
    uidRegex: ^.*Concrete$
- include:
    uidRegex: ^Efl
- include:
    uidRegex: ^Eina
- exclude:
    uidRegex: ^.*
